services:
  postgres:
    image: postgres:16
    container_name: cryptopal-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./zyptox-db/db/init-scripts:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cryptopal-redis
    ports:
      - "6379:6379"

volumes:
  pg_data: